# Generated by Django 5.1.2 on 2024-10-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="time_to_complete",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Время на выполнение привычки"
            ),
        ),
    ]
