# Generated by Django 5.1.2 on 2024-10-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habits_time_to_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="next_reminde",
            field=models.DateField(
                auto_now_add=True,
                null=True,
                verbose_name="Время, когда необходимо выполнить следующий раз привычку",
            ),
        ),
    ]
